[versions]
checkstyle = "10.12.7"
jib = "3.4.0"
git-properties = "2.4.1"
protobuf-plugin = "3.4.0"

[libraries]
[libraries.checkstyle]
group = "com.puppycrawl.tools"
name = "checkstyle"
version.ref = "checkstyle"

[plugins]
[plugins.jib]
id = "com.google.cloud.tools.jib"
version.ref = "jib"

[plugins.git-properties]
id = "com.gorylenko.gradle-git-properties"
version.ref = "git-properties"

[plugins.protobuf]
id = "com.google.cloud.tools.jib"
version.ref = "protobuf-plugin"
