name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]')"
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v2
      - name: 'Setup: Node.js'
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 16.13.0
      - name: 'Setup: update npm'
        run: npm install -g npm
      - name: 'Setup: Java'
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17.x'
      - name: 'Setup: check tools'
        run: |
          node -v
          npm -v
          java -version
      - name: 'Init: cache local Maven repository'
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: 'Init: install Node.js packages'
        run: npm ci
      - name: 'Check: prettier'
        run: npm run prettier:check
      - name: 'Test: run backend tests'
        run: |
          chmod +x mvnw
          ./mvnw clean verify
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ./target/jacoco/jacoco.xml
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (
