name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v2
      - name: 'Setup: Node.js'
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 16.13.0
      - name: 'Setup: update npm'
        run: npm install -g npm
      - name: 'Setup: Java 17'
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17.x'
      - name: 'Setup: check tools'
        run: |
          node -v
          npm -v
          java -version
      - name: 'Init: cache local Maven repository'
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: 'Init: install Node.js packages'
        run: npm ci
      - name: 'Check: prettier'
        run: npm run prettier:check
      - name: 'Test: run backend tests'
        run: |
          chmod +x mvnw
          ./mvnw clean verify
      # - name: codecov
      #   uses: codecov/codecov-action@v2
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     files: jacoco.xml
      #     fail_ci_if_error: true
      #     verbose: true
      - name: 'Report: JaCoCo'
        uses: actions/upload-artifact@v2
        with:
          name: jacoco
          path: '${{ github.workspace }}/target/jacoco'
          retention-days: 1
  codecov:
    needs: test
    name: codecov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: jacoco
      - name: 'debug'
        run: |
          pwd
          ls -al
      - name: codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: jacoco.xml
          fail_ci_if_error: true
          verbose: true
